### PR TITLE
`cargo-sweep` support

### LINKED ISSUE #24: Remove unused dependencies before saving cache
Every time `cargo-cache` falls back on an older cache, it may pull in cargo cache files that are no longer needed, e.g. for an older version of a dependency after a `cargo update`. The stale cargo cache files get mixed in with the fresh cargo cache files produced by `cargo` during the workflow job, which progressively balloons the cache size each time this happens (until the next Rust update comes along and all the caches automatically reset because they can't fall back).

Increasing cache size means increasing download and upload time, and quickly running out of the 10GB cache storage space provided by GitHub. A user would have to recognize that this issue is occurring and know to manually delete all the caches periodically to work around this.

This was mitigated for a particularly bad case in https://github.com/Leafwing-Studios/cargo-cache/issues/22, but the root cause has not yet been fixed.

The ideal solution would be to fall back on an older cache, run the workflow job, then delete any cargo cache files that went unused during the workflow job before saving the cache.

There's an unstable `cargo` feature that may help with this: https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#manual-garbage-collection-with-cargo-clean.

### PR DESCRIPTION
**Pull request by BD103**
This adds initial integration with [BD103/cargo-sweep](https://github.com/BD103/cargo-sweep), closing #24 and https://github.com/BD103/cargo-sweep/issues/4. It is opt-in and intended to be released in v2.3.0 as a non-breaking change.

My plan after this is merged is as follows:

1. https://github.com/BD103/cargo-sweep/issues/6
2. https://github.com/BD103/cargo-sweep/issues/1
3. Make `sweep-cache` true by default as part of v3.0.0 release
4. Improve documentation of `cargo-sweep` in general

### CODE REVIEW

**Comment by TimJentzsch** [comment]
Do you have an example run of this version available?

**Comment by BD103** [comment]
> Do you have an example run of this version available?

Yup! In [this run](https://github.com/BD103/cargo-cache-sweep/actions/runs/10508626655/job/29112926747) I generated a cache that depends on Bevy 0.12, and in [this run](https://github.com/BD103/cargo-cache-sweep/actions/runs/10508873384/job/29113727794) downloaded the existing cache, updated to Bevy 0.14, and purged 1.3 GiB from `target` before uploading it again.

[This](https://github.com/BD103/cargo-cache-sweep/blob/7d1453d6f6e159d790ebb1e38d68cfb4fdf5a8ae/.github/workflows/ci.yml) is the original workflow file, which is pretty bare-bones.

**Review by TimJentzsch — APPROVED** [review]
Looks good, post actions seem to run in the correct order and second run cleaned up 1.3 GB which would pile up otherwise.

Let's try it out!
I won't be able to trigger the release until Saturday or Sunday though.

**Comment by TimJentzsch** [comment]
Oh actually, @BD103 can you add the new input parameters to the Readme as well before we merge this?

**Comment by BD103** [comment]
> Oh actually, @BD103 can you add the new input parameters to the Readme as well before we merge this?

Good catch! I'll get this done by Saturday.

**Comment by BD103** [comment]
Sorry for taking so long, but the `README.md` is now updated!

**Comment by BD103** [comment]
I've just released [v1.3.0](https://github.com/BD103/cargo-sweep/releases/tag/v1.3.0), which exposes `cargo-sweep` caching as you suggested.

With this, I've now "hidden" prebuilt binaries so that they can no longer be enabled. Caching is preferred because it just requires trust in <https://crates.io>, as compared to a random artifact uploaded to Github.

**Review by alice-i-cecile — APPROVED** [review]

**Review by TimJentzsch — APPROVED** [review]
Let's try it out :)

**Comment by TimJentzsch** [comment]
I can probably release this tomorrow.
If not, feel free to ping me on Discord :)

**Comment by BD103** [comment]
> I can probably release this tomorrow. If not, feel free to ping me on Discord :)

Alice gave me collaborator privileges, so I can do so as well! (If you don't get to it first :smile:)

**Pull request merged**
